const initial = {
  blackgreen: {
    buttons: 'green',
    USB_rack: 'black',
    USB_output: 'conifer',
    ventilation_buttons: 'black',
    ventilation: 'black',
    cheat_buttons: 'black',
    rpi_back_w_selector: 'conifer',
    rpi_back: 'conifer',
    leg: 'conifer',
    side_left: 'malachite',
    side_right: 'malachite',
    side_base: 'black',
    side_back: 'black',
    side_front: 'black',
    side_top: 'black'
  },
  blackblue: {
    buttons: 'blue',
    USB_rack: 'black',
    USB_output: 'black',
    ventilation_buttons: 'black',
    ventilation: 'black',
    cheat_buttons: 'black',
    rpi_back_w_selector: 'black',
    rpi_back: 'black',
    leg: 'black',
    side_left: 'summerSky',
    side_right: 'summerSky',
    side_base: 'black',
    side_back: 'black',
    side_front: 'black',
    side_top: 'black'
  },
  blackred: {
    buttons: 'red',
    USB_rack: 'black',
    USB_output: 'black',
    ventilation_buttons: 'black',
    ventilation: 'black',
    cheat_buttons: 'black',
    rpi_back_w_selector: 'black',
    rpi_back: 'black',
    leg: 'red',
    side_left: 'redOrange',
    side_right: 'redOrange',
    side_base: 'black',
    side_back: 'black',
    side_front: 'black',
    side_top: 'black'
  },
  whitegreen: {
    buttons: 'green',
    USB_rack: 'white',
    USB_output: 'white',
    ventilation_buttons: 'white',
    ventilation: 'white',
    cheat_buttons: 'white',
    rpi_back_w_selector: 'white',
    rpi_back: 'white',
    leg: 'conifer',
    side_left: 'malachite',
    side_right: 'malachite',
    side_base: 'white',
    side_back: 'white',
    side_front: 'white',
    side_top: 'white'
  },
  whiteblue: {
    buttons: 'blue',
    USB_rack: 'white',
    USB_output: 'white',
    ventilation_buttons: 'white',
    ventilation: 'white',
    cheat_buttons: 'white',
    rpi_back_w_selector: 'white',
    rpi_back: 'white',
    leg: 'white',
    side_left: 'summerSky',
    side_right: 'summerSky',
    side_base: 'white',
    side_back: 'white',
    side_front: 'white',
    side_top: 'white'
  },
  whitered: {
    buttons: 'red',
    USB_rack: 'red',
    USB_output: 'red',
    ventilation_buttons: 'red',
    ventilation: 'red',
    cheat_buttons: 'red',
    rpi_back_w_selector: 'red',
    rpi_back: 'red',
    leg: 'red',
    side_left: 'redOrange',
    side_right: 'redOrange',
    side_base: 'white',
    side_back: 'white',
    side_front: 'white',
    side_top: 'white'
  },
  monocrome_white: {
    buttons: 'white',
    USB_rack: 'black',
    USB_output: 'black',
    ventilation_buttons: 'black',
    ventilation: 'black',
    cheat_buttons: 'black',
    rpi_back_w_selector: 'white',
    rpi_back: 'white',
    leg: 'white',
    side_left: 'white',
    side_right: 'white',
    side_base: 'black',
    side_back: 'black',
    side_front: 'black',
    side_top: 'black'
  },
  monocrome_black: {
    buttons: 'black',
    USB_rack: 'white',
    USB_output: 'white',
    ventilation_buttons: 'white',
    ventilation: 'white',
    cheat_buttons: 'white',
    rpi_back_w_selector: 'black',
    rpi_back: 'black',
    leg: 'black',
    side_left: 'black',
    side_right: 'black',
    side_base: 'white',
    side_back: 'white',
    side_front: 'white',
    side_top: 'white'
  }
}

export const reducer = (state = initial, action = {}) => {
  return state;
};

export default reducer;